name: Gradle Build

on: push

jobs:
  build:
    runs on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant executive permission for gradlew
        run: chmod +x gradlew

      - name: Unit Tests
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

  ktlint:
    name: Check Code Quality
      runs-on: ubuntu-latest

      steps:
        - name: Clone PR
          uses: actions/checkout@v2
          with:
            fetch-depth: 1
        - name: Run Ktlint
          uses: lucasnlm/ktlint-action@master
